_wandb:
    value:
        cli_version: 0.22.1
        e:
            fdwwp6ban8el5owp8zftbcdnxjoem1x1:
                apple:
                    ecpuCores: 4
                    gpuCores: 40
                    memoryGb: 48
                    name: Apple M3 Max
                    pcpuCores: 12
                    ramTotalBytes: "51539607552"
                    swapTotalBytes: "13958643712"
                codePath: text_cnn.py
                codePathLocal: text_cnn.py
                cpu_count: 16
                cpu_count_logical: 16
                disk:
                    /:
                        total: "994662584320"
                        used: "585863213056"
                email: mark.karamyar@gmail.com
                executable: /Users/mark/dev/cu-stuff/ag-news-classification/.venv/bin/python3
                git:
                    commit: 37abec4d356596d2ce83fac7a863e40cb88ecbb0
                    remote: git@github.com:devmarkpro/ag-news-classification.git
                host: Nastarans-MacBook-Pro.local
                memory:
                    total: "51539607552"
                os: macOS-26.0.1-arm64-arm-64bit-Mach-O
                program: /Users/mark/dev/cu-stuff/ag-news-classification/text_cnn.py
                python: CPython 3.13.5
                root: /Users/mark/dev/cu-stuff/ag-news-classification
                startedAt: "2025-10-06T05:59:24.804024Z"
                writerId: fdwwp6ban8el5owp8zftbcdnxjoem1x1
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 5
                - 35
                - 40
                - 53
            "2":
                - 1
                - 5
                - 35
                - 40
                - 53
            "3":
                - 1
                - 2
                - 13
                - 15
                - 16
            "4": 3.13.5
            "5": 0.22.1
            "12": 0.22.1
            "13": darwin-arm64
batch_size:
    value: 256
channels:
    value: 256
dropout:
    value: 0.5
emb_dim:
    value: 200
epochs:
    value: 15
grad_clip:
    value: 1.5
kernel_sizes:
    value:
        - 2
        - 3
        - 4
        - 5
lr:
    value: 0.001982169925018568
max_len:
    value: 200
optimizer:
    value: adam
patience:
    value: 5
weight_decay:
    value: 1.9378094205564048e-05
