_wandb:
    value:
        cli_version: 0.22.1
        e:
            vd9q248njjdsypdeo2nhddngh1kijklr:
                apple:
                    ecpuCores: 4
                    gpuCores: 40
                    memoryGb: 48
                    name: Apple M3 Max
                    pcpuCores: 12
                    ramTotalBytes: "51539607552"
                    swapTotalBytes: "11811160064"
                codePath: text_cnn.py
                codePathLocal: text_cnn.py
                cpu_count: 16
                cpu_count_logical: 16
                disk:
                    /:
                        total: "994662584320"
                        used: "583719211008"
                email: mark.karamyar@gmail.com
                executable: /Users/mark/dev/cu-stuff/ag-news-classification/.venv/bin/python3
                git:
                    commit: 37abec4d356596d2ce83fac7a863e40cb88ecbb0
                    remote: git@github.com:devmarkpro/ag-news-classification.git
                host: Nastarans-MacBook-Pro.local
                memory:
                    total: "51539607552"
                os: macOS-26.0.1-arm64-arm-64bit-Mach-O
                program: /Users/mark/dev/cu-stuff/ag-news-classification/text_cnn.py
                python: CPython 3.13.5
                root: /Users/mark/dev/cu-stuff/ag-news-classification
                startedAt: "2025-10-06T05:49:40.426595Z"
                writerId: vd9q248njjdsypdeo2nhddngh1kijklr
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 5
                - 35
                - 40
                - 53
            "2":
                - 1
                - 5
                - 35
                - 40
                - 53
            "3":
                - 1
                - 2
                - 13
                - 15
                - 16
            "4": 3.13.5
            "5": 0.22.1
            "10":
                - 20
            "12": 0.22.1
            "13": darwin-arm64
batch_size:
    value: 64
channels:
    value: 192
device:
    value: mps
dropout:
    value: 0.5
emb_dim:
    value: 100
epochs:
    value: 20
grad_clip:
    value: 1
kernel_sizes:
    value:
        - 3
        - 4
        - 5
        - 6
lr:
    value: 0.0024764628875038144
max_len:
    value: 200
optimizer:
    value: adam
patience:
    value: 3
trial_number:
    value: 19
vocab_size:
    value: 50000
weight_decay:
    value: 4.6935455931059695e-06
