_wandb:
    value:
        cli_version: 0.22.1
        e:
            9xqmcka8xni6ng9ums9one2itynk0vhd:
                apple:
                    ecpuCores: 4
                    gpuCores: 40
                    memoryGb: 48
                    name: Apple M3 Max
                    pcpuCores: 12
                    ramTotalBytes: "51539607552"
                    swapTotalBytes: "7516192768"
                codePath: text_cnn.py
                codePathLocal: text_cnn.py
                cpu_count: 16
                cpu_count_logical: 16
                disk:
                    /:
                        total: "994662584320"
                        used: "579279265792"
                email: mark.karamyar@gmail.com
                executable: /Users/mark/dev/cu-stuff/ag-news-classification/.venv/bin/python3
                git:
                    commit: 37abec4d356596d2ce83fac7a863e40cb88ecbb0
                    remote: git@github.com:devmarkpro/ag-news-classification.git
                host: Nastarans-MacBook-Pro.local
                memory:
                    total: "51539607552"
                os: macOS-26.0.1-arm64-arm-64bit-Mach-O
                program: /Users/mark/dev/cu-stuff/ag-news-classification/text_cnn.py
                python: CPython 3.13.5
                root: /Users/mark/dev/cu-stuff/ag-news-classification
                startedAt: "2025-10-06T04:58:27.778101Z"
                writerId: 9xqmcka8xni6ng9ums9one2itynk0vhd
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 5
                - 35
                - 40
                - 53
            "2":
                - 1
                - 5
                - 35
                - 40
                - 53
            "3":
                - 1
                - 2
                - 13
                - 15
                - 16
            "4": 3.13.5
            "5": 0.22.1
            "10":
                - 20
            "12": 0.22.1
            "13": darwin-arm64
batch_size:
    value: 128
channels:
    value: 128
device:
    value: mps
dropout:
    value: 0.2
emb_dim:
    value: 300
epochs:
    value: 20
grad_clip:
    value: 1
kernel_sizes:
    value:
        - 3
        - 4
        - 5
        - 6
lr:
    value: 0.003446174676174919
max_len:
    value: 160
optimizer:
    value: adamw
patience:
    value: 3
trial_number:
    value: 6
vocab_size:
    value: 50000
weight_decay:
    value: 5.730901320938438e-05
